### ISSUE TITLE
Another language

### ISSUE THREAD

**Issue by kotchuprik** [JWHennessey/phpInsight#19]
Hi JWHennessey!

I want to use your the beautiful library for Spanish language. Can you write a small readme about internationalization dictionaries? Maybe have an article that I should study for this?

**Comment by JWHennessey** [comment]
Hi, 
Apologies for my delayed reply, I was hoping to write a short explanation for you but I haven't had time. It shouldn't be too difficult for yourself to add a dictionary for another language. You will simply need to replace the dictionaries (stored as PHP array) in /lib/PHPInsight/dictionaries/, of which there are 5. 

source.ign.php - Ignore words. These are words that do not indicate the sentiment and shouldn't be used in the classification. 

source.prefix.php - Prefix works. These words when prefixed with a words that indicated sentiment changes the meaning. e.g not good

source.pos.php - Positive words. These are words that indicate sentiment is positive 

source.neg.php - Negative words. These are words that indicate sentiment is negative

source.neu.php - Neutral words. These are words that indicate sentiment is neutral 

Best of luck!

**Comment by kotchuprik** [comment]
Thank you!
