### ISSUE TITLE
Surely `best` is positive?

### ISSUE THREAD

**Issue by georgecrawford** [JWHennessey/phpInsight#20]
Thanks so much for this - it's working very well for my requirements. I'm surprised to see that the word `best` is not in the positive dictionary, so the phrase `the best in the world` comes up as Neutral (score 0.333 for each class). Can you explain where the dictionary was pulled from, and would you accept a PR to fix this?

**Comment by JWHennessey** [comment]
I'm surprised too and I would certainly accept a PR for this. 

I can't remember from the top of my head where the dictionary came from. I'll try and find my undergraduate thesis as it should be noted in there and let you know.

**Comment by JWHennessey** [comment]
In my report I cited the following link - http://people.cs.pitt.edu/~wiebe/resources.html - however it now returns a 404. 

Jan Wiebe's webpage now has a link - http://mpqa.cs.pitt.edu/ - but I can't be certain if the dataset I used is there.
