### ISSUE TITLE
Undefined variable $data

### ISSUE THREAD

**Issue by alinf** [JWHennessey/phpInsight#22]
On line 265:

if(file_exists($data)){
	$this->dataFolder = $dataFolder;
}
Shouldn't it be:
if(file_exists($dataFolder)){
	$this->dataFolder = $dataFolder;
}

**Comment by hypeJunction** [comment]
You can reference code lines by clicking on the line number and copying/pasting the URL from the address bar. Saves us all time :) https://github.com/JWHennessey/phpInsight/blob/master/lib/PHPInsight/Sentiment.php#L265

It does look like it should be ```$dataFolder```

**Comment by JWHennessey** [comment]
Thanks for pointing this out. I have corrected and pushed the fix.
