### ISSUE TITLE
Please add the letter repetition 

### ISSUE THREAD

**Issue by misterfifi1** [JWHennessey/phpInsight#23]
Could you add this feature to improve the score of each category if a letter is repeated?

FYI:  
Repeating letters - if you look at the tweets, sometimes people repeat letters to stress the emotion. E.g. hunggrryyy, huuuuuuungry for 'hungry'. We can look for 2 or more repetitive letters in words and replace them by 2 of the same.

[Link](http://ravikiranj.net/posts/2012/code/how-build-twitter-sentiment-analyzer/)

**Comment by JWHennessey** [comment]
This is an interesting suggestion and something I haven't thought about - thanks. 

I don't think I'll be able to implement this feature in the near future but feel free to submit a pull request.
