### ISSUE TITLE
Negative Statement?

### ISSUE THREAD

**Issue by mediaslave** [JWHennessey/phpInsight#24]
Hey,  I have the following and I am wondering how I can help train the system.  I feel like this is a positive statement, but it gave a negative response.

    Kudos to Villanovense for not playing dirty

Any help would be great!

**Comment by mediaslave** [comment]
More details, sorry.

I have added the word "kudos" and "notplayingdirty" to the positive dictionary without success.  Not sure if that is how that works.  

Thanks!

**Comment by JWHennessey** [comment]
Hello, 
The method will only concatenate pairs of words and look for them in the dictionary e.g "not playing" and "playing dirty". You will need to adjust the algorithm to concatenate triplets of words and search the dictionary. 
Good luck!
