### ISSUE TITLE
is it possible to add new languange

### ISSUE THREAD

**Issue by jazwethinkweizm** [JWHennessey/phpInsight#25]
hi there, is it possible to add new language or add new negative/positive dictionaries ?
any clue how to do it ?
i'm newbies on this, thanks for your time give me explanation on this.

**Comment by JWHennessey** [comment]
Hello!
Yes it is possible to change dictionaries to support a new language. You could do this in two ways:
Replace the current dictionaries in lib/PHPInsight/dictionaries/ using the same filenames. Or you could create new dictionaries with the same naming convention e.g. source.pos_spanish.php then update any reference to the dictionaries in lib/PHPInsight/Sentiment.php e.g line 68 to  private $classes = array('pos_spanish', 'neg_spanish', 'neu_spanish'); note there will be more places that refer to the dictionaries. 

For reference the dictionaries are as follows:
ign - words to ignore
neg - negative words
neu - neutral words
pos - positive words
prefix - prefix words that can change meaning of sentence e.g 'not' is a prefix word as 'not good'  changes the meaning of the positive word 'good'

I hope this helps!

**Comment by jazwethinkweizm** [comment]
i just insert new word on your array negative word in lib/PHPInsight/dictionaries/source.neg.php, then i try to prove that it should be negative sentiment, but it doesn't work, turns out into Neutral.
am i make any mistake step here..
thanks for your help.
