### ISSUE TITLE
Use phpInsight for foreign languages

### ISSUE THREAD

**Issue by Dzonny** [JWHennessey/phpInsight#27]
Hey there,

Just wondering if I can use this tool for foreign languages rather than English, and if so, I should build a list of positive/negative/neutral words/phrases manually, and add it within this tool, right? Just asking.

Thanks so much!

**Comment by hypeJunction** [comment]
Check closed issues. Been answered before

**Comment by stephanvierkant** [comment]
See #19

**Comment by gmaximowicz** [comment]
Hi! i want to know if somebody has a sample list for the spanish dictionary, or know a repository we can use for start one.
