### ISSUE TITLE
Change to Other Algorithm

### ISSUE THREAD

**Issue by inyong92** [JWHennessey/phpInsight#32]
Hello Mr. JWHennessey

Is that possible to change naive bayes algorithm to other one? let say kNN (k nearest algorithm), or the other. If that can, in which part from the code should be changed? does it only in sentiment.php file or also data file?
Thank you..

**Comment by JWHennessey** [comment]
Yes, you could change to a different algorithm and sentiment.php would be the place to do it. I'm not sure if the data included is well designed for knn, ideally you would have examples of classified sentences organised a one-hot vectors then doing knn is simple. This data is organised as a bag of words model making knn more tricky but you might be able to think of something.
